services:
  coco-frontend:
    container_name: coco-frontend
    tty: true
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile.prod
      args:
        - NODE_IMAGE_TAG=${NODE_IMAGE_TAG:-21.5-bullseye-slim} # Node image tag
        - NGINX_IMAGE_TAG=${NGINX_IMAGE_TAG:-1.24-alpine} # Nginx image tag
    ports:
      - ${FRONTEND_PORT:-6500}:6500
    networks:
      - app-network

  coco-backend:
    container_name: coco-backend
    tty: true
    init: true # Properly handles running as PID 1 inside a container. Source: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
    build:
      context: . # Set to root so backend has access to frontend package.json for parsing
      dockerfile: ./backend/.docker/Dockerfile.prod
      args:
        - NODE_IMAGE_TAG=${NODE_IMAGE_TAG:-21.5-bullseye-slim} # Node image tag
    env_file: .env
    ports:
      - ${BACKEND_PORT:-6600}:6600
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"
