ARG NODE_IMAGE_TAG
ARG NGINX_IMAGE_TAG

FROM node:${NODE_IMAGE_TAG} as build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

FROM nginx:${NGINX_IMAGE_TAG} as prod

COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/build .

RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx

EXPOSE 6500

ENTRYPOINT ["nginx", "-g", "daemon off;"]
