name: CI Unit Integration Test Suite 

on:
  pull_request:
    types: [opened, synchronize, ready_for_review] # Triggered by opened or changed pull requests.
    branches: [ main ]
  workflow_dispatch:

jobs: 
  ci-unit-integration-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:  
          ref: main
          fetch-depth: 0

      - name: Get Last Commit on Main
        run: |
          FIRST_COMMIT=$(git rev-parse HEAD)
          echo "FIRST_COMMIT=$FIRST_COMMIT" >> $GITHUB_ENV

      - name: Check branch of Pull Request
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get Last Commit on Pull Request
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_ENV

      - name: Output Path Logic
        id: pull-request-diff-path
        run: |
          if git diff --name-only ${{ env.FIRST_COMMIT }} ${{ env.LAST_COMMIT }} | grep -q '^backend'; then
            echo "diff=backend" >> $GITHUB_OUTPUT
          else
            echo "diff=frontend" >> $GITHUB_OUTPUT
          fi
          
      - name: Run API Test Suite if diff lives in ./backend/**
        working-directory: ./backend
        if: ${{ steps.pull-request-diff-path.outputs.diff == 'backend' }}
        run: |
          npm i 
          npm run test
        
      - name: Run Frontend Test Suite if diff lives in ./frontend/**
        working-directory: ./frontend
        if: ${{ steps.pull-request-diff-path.outputs.diff == 'frontend' }}
        run: |
          npm i
          npm run test
