# GitHub Actions workflow for deploying API image to TEST env
name: API - GitOps Update TEST Image

on:
  workflow_dispatch:
      inputs:
        image_tag:
          description: 'Image Tag to deploy'
          required: true

env:
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}
  ENVIRONMENT: 'test'

jobs:
  update-gitops-image-tag:
    runs-on: ubuntu-latest
    steps:

      # Install yaml parser
    - name: Install yq
      run: |
        curl -Lo yq "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
        chmod +x yq
        mv yq /home/runner/bin

      # Add deploy key to runner
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITOPS_REPO_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # Make changes to image tag in values.yaml within GitOps repo
    - name: Clone, Update, and Commit Changes
      run: |
        git clone git@github.com:bcgov-c/tenant-gitops-baf95e.git
        cd tenant-gitops-baf95e

        FILE_PATH="common-code/values-test.yaml"
        NEW_TAG="${{ steps.get-pr-number.outputs.result }}"

        yq e ".api.imageTag = \"${{ env.IMAGE_TAG }}\"" -i "$FILE_PATH"

        git config user.email "adam.kroon@gov.bc.ca"
        git config user.name "akroon3r"

        git add "$FILE_PATH"

        git commit -m "Update API image tag to $NEW_TAG"

        git push
