# Credit @bottle7 Brandon Bouchard for creating this script to update image tags in gitops repos for Argo CD Deployments

name: Frontend - GitOps Update DEV Image

on:
  push:
    branches:
    - main
    paths:
    - frontend/**

jobs:

  update-gitops-image-tag:
    runs-on: ubuntu-latest
    
    env:
      GH_TOKEN: ${{ github.token }}
      
    steps:
    - name: Get PR Number
      id: get-pr-number
      uses: actions/github-script@v5
      with:
        script: |
          const { data: pulls } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'all',
          });
          const pr = pulls.find(pr => pr.merge_commit_sha === process.env.GITHUB_SHA);

          if (pr) {
            return pr.number
          } else {
            return ''
          }

        result-encoding: string

      # Install yaml parser
    - name: Install yq
      run: |
        curl -Lo yq "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
        chmod +x yq
        mv yq /home/runner/bin

      # Add deploy key to runner
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITOPS_REPO_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # Make changes to image tag in values.yaml within GitOps repo
    - name: Clone, Update, and Commit Changes
      run: |
        git clone git@github.com:bcgov-c/tenant-gitops-baf95e.git
        cd tenant-gitops-baf95e

        FILE_PATH="common-code/values-dev.yaml"
        NEW_TAG="${{ steps.get-pr-number.outputs.result }}"

        yq e ".frontend.imageTag = \"$NEW_TAG\"" -i "$FILE_PATH"

        git config user.email "adam.kroon@gov.bc.ca"
        git config user.name "akroon3r"

        git add "$FILE_PATH"

        git commit -m "Update Frontend image tag to $NEW_TAG"

        git push

    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Clone the wiki repository
    - name: Clone wiki repository
      run: |
        echo "Cloning wiki repo https://github.com/$GITHUB_REPOSITORY.wiki.git"
        git clone "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git" ./wiki

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    # Run the update wiki Python script
    - name: Run update wiki Python script
      run: python ./.github/helpers/update-wiki-table.py ./wiki/Image-tags.md "CoCo APP" "Deployed Image Tag in DEV" "${{ steps.get-pr-number.outputs.result }}"

    # Commit and push changes to the wiki
    - name: Commit and push changes to wiki
      run: |
        cd ./wiki
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        if git diff-index --quiet HEAD; then
          echo "Nothing changed"
          exit 0
        fi
        echo "Pushing changes to wiki"
        git commit -m "Value populated at image build API" && git push "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git"

    # Add comment to the PR
    - name: Add Comment To the PR
      if: github.event.action == 'opened'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🚀 **Deployment Information**\n\nThe CoCo Demo App Image has been built with the tag: **`${{ steps.get-pr-number.outputs.result }}`**. Please make sure to utilize this specific tag when promoting these changes to the TEST and PROD environments during the API deployment. For more updates please monitor [Image Tags](https://github.com/bcgov/PIMS/wiki/Image-tags) Page on Wiki."
          })
