# Credit @bottle7 Brandon Bouchard for creating this script to update image tags in gitops repos for Argo CD Deployments

name: GitOps - Update DEV API imageTag

on:
  push:
    branches:
    - main
    paths:
    - backend/**

jobs:
  update-gitops-image-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR Number
      id: get-pr-number
      uses: actions/github-script@v5
      with:
        script: |
          const { data: pulls } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'all',
          });
          const pr = pulls.find(pr => pr.merge_commit_sha === process.env.GITHUB_SHA);

          if (pr) {
            return pr.number
          } else {
            return ''
          }

        result-encoding: string

      # Install yaml parser
    - name: Install yq
      run: |
        curl -Lo yq "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
        chmod +x yq
        mv yq /home/runner/bin

      # Add deploy key to runner
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITOPS_REPO_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # Make changes to image tag in values.yaml within GitOps repo
    - name: Clone, Update, and Commit Changes
      run: |
        git clone git@github.com:bcgov-c/tenant-gitops-baf95e.git
        cd tenant-gitops-baf95e

        FILE_PATH="common-code/values-dev.yaml"
        NEW_TAG="${{ steps.get-pr-number.outputs.result }}"

        yq e ".api.imageTag = \"$NEW_TAG\"" -i "$FILE_PATH"

        git config user.email "adam.kroon@gov.bc.ca"
        git config user.name "akroon3r"

        git add "$FILE_PATH"

        git commit -m "Update API image tag to $NEW_TAG"

        git push

    - name: Checkout Common Code Repo
      uses: actions/checkout@v3

    # Clone wiki repository
    - name: Clone Repository with Wiki Artifact
      run: |
        echo "Cloning wiki repo https://github.com/$GITHUB_REPOSITORY.wiki.git"
        git clone "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git" ./wiki
    
    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    # Run update wiki python script
    - name: Run update wiki python script
      run: python ./.github/helpers/update-wiki-table.py ./wiki/Image-tags.md 'CoCo API' "Deployed Image Tag in DEV" "${{ steps.get-pr-number.outputs.result }}"
    
    # Commit and push changes to wiki
    - name: Commit and push changes to wiki
      run: |
        cd ./wiki
        git config user.name "akroon3r"
        git config user.email "adam.kroon@gov.bc.ca"
        git add .
        if git diff-index --quiet HEAD; then
          echo "Nothing changed"
          exit 0
        fi
        echo "Pushing changes to wiki"
        git commit -m "Value populated at Deploy CoCo API" && git push "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.wiki.git"
